# Generated by Django 3.1.7 on 2021-03-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crear_pokemones',
            name='id_pokemon',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crear_pokemones',
            name='foto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
