# Generated by Django 3.1.7 on 2021-03-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upokemon', '0002_auto_20210324_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crear_pokemones',
            name='id_pokemon',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
